### ISSUE TITLE
New feature request: Status web page

### ISSUE THREAD

**Issue by dvinik** [qdm12/gluetun-wiki#10]
Thank you for this wonderful project. It would be great if there would be a quick way to connect to a gluetun instance via browser to check connection status, statistics, and health. added bonus would be a web interface to manage connections(e.g., add servers, connect to servers, pause traffic).

**Comment by qdm12** [comment]
This is in my crosshair, although it might be as a paid mobile app (trying to monetize this 😉).
There is still quite a bit of work needed until this is even feasible on the gluetun side of thing, so please be patient (a few months patient 😄). I'll close this since this is a long ongoing process already in motion, but thanks for the suggestion 👍

**Comment by dvinik** [comment]
Thanks, I’ll be your first customer for the app. You do great work.


Best regards,

David Vinik

On Sep 24, 2023, at 10:19 PM, Quentin McGaw ***@***.***> wrote:

﻿

Closed #10<https://github.com/qdm12/gluetun-wiki/issues/10> as not planned.
