### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by privacyguy123** [qdm12/gluetun-wiki#14]
Forgive my ignorance - is there some reason why Https wouldn't be supported for the proxy options?

**Comment by qdm12** [comment]
Subscribe to issue https://github.com/qdm12/gluetun/issues/278

For now, you can only use shadowsocks which is encrypted.

It's not a total priority, since the http proxy is really here for 'limited' LAN devices  like old TVs which can't connect through shadowsocks. Most devices can get a shadowsocks client installed, which is preferable.
