### ISSUE TITLE
NordVPN WireGuard: ERROR VPN settings: Wireguard settings: private key is not valid: wgtypes: incorrect key size: 48

### ISSUE THREAD

**Issue by Pyroluk** [qdm12/gluetun-wiki#18]
Hi@all,

today I was trying to start my previously working NordVPN WireGuard setup, but I now get this error:
`ERROR VPN settings: Wireguard settings: private key is not valid: wgtypes: incorrect key size: 48`

I created a new access token on NordVPN’s website but the problem persists.
Seems like someone at NordVPN felt the need to mess with the WireGuard configuration again...

Any ideas how to regain compatibility?

Cheers 🤙

**Comment by aftertommy** [comment]
I'm seeing the same thing

**Comment by cospeedster** [comment]
Hey guys,

the access token is not the private key.

I used this to get my private key: https://gist.github.com/bluewalk/7b3db071c488c82c604baf76a42eaad3

**Comment by qdm12** [comment]
Thanks @cospeedster that likely solves it.
I changed the Gluetun code in https://github.com/qdm12/gluetun/commit/8318be3159ec144bbaaeb5417231773f0b234c38 to log a warning `you might be using your access token instead of the Wireguard private key` if it sees the error `wgtypes: incorrect key size: 48` AND nordvpn is the provider in use.
