### ISSUE TITLE
custom.conf file

### ISSUE THREAD

**Issue by SlyJoker** [qdm12/gluetun-wiki#33]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/openvpn-configuration-file.md

### What's missing?

I'm trying to follow the outlined steps for setting up a custom openvpn, but I cannot for the life of me find any example of a .conf file mentioned. I have the openvpn zip folder with two Security Certificates, and various .ovpn files. Do I just rename one of the .ovpn files to .conf? Do I create a new .conf file? What's the syntax / structure?

TB supports Wireguard, but I I don't believe they share or provide obvious access to the various Wireguard keys needed, so I figured I'd try the more "simple" OpenVPN method instead.

Context: I have a paid TunnelBear sub and want to try getting it setup, but TB isn't currently supported (that's fine), but I want to at least try getting the custom.md setup.

**Comment by swatcats** [comment]
+1, I cant find any examples of an OpenVPN custom.conf file.

**Comment by swatcats** [comment]
After tinkering with it for awhile, i noticed a line in the container logs saying that the custom.conf file did not have a remote. This seems to be the remote option from the OpenVPN config file. I copied the contents of my .ovpn file into the custom.conf file from my provider and it started working. Hopefully this link will help some people, it has a list of some of the popular OpenVPN tunnel options that you may want to configure.

# OpenVPN Reference Manual
https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/

**Comment by qdm12** [comment]
> I have the openvpn zip folder with two Security Certificates, and various .ovpn files. Do I just rename one of the .ovpn files to .conf? Do I create a new .conf file? What's the syntax / structure?

Essentially just pick whatever .ovpn (or .conf) file and use that. Both file extensions are the same (no clue why that is), see https://superuser.com/a/1104472

The documentation mentions

> In the following we assume your custom openvpn configuration file is named `custom.conf`.

So there is no indication it MUST be custom.conf, any other name works as well. I've added "Note this can be named something else, for example `autralia.ovpn`." just to make it clearer.

> I cant find any examples of an OpenVPN custom.conf file.

Yes, because that 100% depends on the VPN server which I have no control over. Anyway, with the added text mentioning it could be with the .ovpn extension, that should remove any doubt concerning the syntax for the config file.
