### ISSUE TITLE
Creating VPN using shadow socks 

### ISSUE THREAD

**Issue by engageub** [qdm12/gluetun-wiki#4]
Hi,
I stumbled upon the wikis but could not find how to connect to shadow socks. There are options to enable internal shadow socks but could not find one to create vpn using shadow socks.
I would like to create a vpn using shadow socks from [pproxy](https://github.com/qwj/python-proxy).
Is it possible using custom.conf.

Since plain socks5 proxy to create vpn is not supported, I thought of creating shadow socks proxy using plain socks proxy and then creating docker vpn using gluetun. 

Thank you

**Comment by qdm12** [comment]
Shadowsocks or socks5 is not a vpn, it's a proxy. Note shadowsocks is NOT a socks5 proxy, it is implemented similarly but has an encryption layer on top given a pre-shared password/key. So it won't work with socks5 client at all, since it's still an entirely different protocol.

There is a built-in shadowsocks proxy server in gluetun you can enable, see https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-lan-device-to-gluetun.md#shadowsocks-proxy

This should clear any confusion and instructions are well detailed on how to use shadowsocks.
