### ISSUE TITLE
Prowlarr cannot connect to Radarr/Sonarr when behind gluetun

### ISSUE THREAD

**Issue by Daive01** [qdm12/gluetun-wiki#52]
Today I was connecting Radarr/Sonarr to Prowlarr, which is using gluetun, and it wouldn't work. So I tried running Prowlarr in a compose file with no connection to gluetun, and it connected just fine. I am on the latest release of all images.

P.S. I am relatively new to this stuff, so the less complicated the solution, the better. 

Thanks

**Comment by Daive01** [comment]
An additional question I have is: is it recommended for flaresolverr to be connected to gluetun or independent?

**Comment by joestump** [comment]
Any service your route through `gluetun` will need that service's ports exposed on the *gluetun container*. When you route traffic through the `gluetun` container that container effectively becomes the internet gateway for those containers. I would try adding `7878:7878` and `8989:8989` to your `gluetun` container's `ports`.

**Comment by DarkVader-cell** [comment]
Facing the same issue here, Radarr/Sonarr are running locally on the system while `Prowlarr` is running in a docker connected to gluetun, @joestump I can even access the `Prowlarr` WebUI through the exposed ports in `gluetun`, it just keeps throwing an error when I try connecting them. 

Adding `7878:7878` and `8989:8989` to the list of exposed ports by `gluetun`is not required since OP is not hosting Radarr/Sonarr in a container connected to `gluetun`

**Comment by qdm12** [comment]
This is not an issue with the Wiki, so closing this. Create a discussion at https://github.com/qdm12/gluetun/discussions instead

**Comment by qdm12** [comment]
Maybe see https://github.com/qdm12/gluetun/issues/2187
