### ISSUE TITLE
"You are running 1 commit behind the most recent latest"

### ISSUE THREAD

**Issue by Daive01** [qdm12/gluetun-wiki#53]
No matter how many times i repull the image it always says "You are running 1 commit behind the most recent latest".

**Comment by qdm12** [comment]
Thanks for reporting this. This is due to the Docker image being built on most commits, but not all. Some commits (for example https://github.com/qdm12/gluetun/commit/8331ce601085c6ae65b7fead463ac542de447c8b) are documentation only commits, and so they don't trigger the build of the image. So there is one more commit, but no docker image associated with it. I could theoretically do some gymnastics with the Github API to figure this out, but let's keep it simple since this is only informational and not really a priority to fix. Closing this, but again, thanks for taking the time to report it!
